services:

  celery:
    volumes:
      - './src:/usr/src/project'
      - './.devcontainer/celery/.vscode:/usr/src/.vscode'
      - statics:/mnt/volumes/statics
      - geoserver-data-dir:/geoserver_data/data
      - backup-restore:/backup_restore
      - data:/data
      - tmp:/tmp
    entrypoint: ["/usr/src/project/entrypoint.sh"]
    command: sleep infinity
