version: '2'

services:
  data_dir_conf:
    build: .
    image: geonode/geoserver_data:2.23.0
    container_name: geoserver_data_dir
    command: /bin/true
    volumes:
      - /geoserver_data/data 

volumes:
  # reference to the named data container that holds the preloaded geoserver data directory 
  geoserver_data_dir: