services:

  django:
    ports:
      - "8000:8000"
    volumes:
      - './src:/usr/src/project'
      - './.devcontainer/django/.vscode:/usr/src/.vscode'
      - statics:/mnt/volumes/statics
      - geoserver-data-dir:/geoserver_data/data
      - backup-restore:/backup_restore
      - data:/data
      - tmp:/tmp
    healthcheck:
      test: "echo 'Alive'"
    entrypoint: ["/usr/src/project/entrypoint.sh"]
    command: sleep infinity
